---
abstract: 'Tapper - Complete OS testing in a box via autotest'
author:
  - 'AMD OSRC Tapper Team, C<< <tapper at amd64.org> >>'
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-TestSuite-AutoTest
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Archive::Tar: 1.76
  File::ShareDir: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  IO::Socket::INET: 0
  Moose: 0
  Sys::Hostname: 0
  Tapper::Base: 3.000010
  YAML::Syck: 0
  perl: 5.10.0
version: 3.000010
